import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

// Initialize Firebase only if `firebase_options.dart` has been generated by
// `flutterfire configure`. Until then, the app still launches without Firebase.
//
// Setup steps:
//   1. Create a Firebase project at https://console.firebase.google.com
//   2. dart pub global activate flutterfire_cli
//   3. flutterfire configure  (generates lib/firebase_options.dart and platform configs)
//   4. Replace this function body with:
//        await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
Future<void> initializeFirebaseIfConfigured() async {
  try {
    await Firebase.initializeApp();
  } catch (e) {
    if (kDebugMode) {
      debugPrint('Firebase not configured yet — skipping. ($e)');
    }
  }
}
